set(BUILD_TARGET_ARCH x86_64)
set(CMAKE_BUILD_TYPE Release)
set(BUILD_SHARED_LIBS OFF)
set(BUILD_STATIC_LIBS ON)

set(ENABLE_BUILD_VMM ON)
set(ENABLE_BUILD_USERSPACE ON)
set(ENABLE_BUILD_TEST OFF)
set(ENABLE_BUILD_EFI OFF)

set(ENABLE_ASAN OFF)
set(ENABLE_TIDY OFF)
set(ENABLE_FORMAT OFF)
set(ENABLE_CODECOV OFF)
set(ENABLE_COMPILER_WARNINGS ON)

set(EXTENSION ${CMAKE_CURRENT_LIST_DIR})
